# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/products_db
      - SECRET_KEY=supersecretkey
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
